### ISSUE TITLE
Possibility of bot only detecting activity from specific channels

### ISSUE THREAD

**Issue by Poodmund** [bhigginsuk/discord-activity-monitor#28]
Would there be any possibility that the bot could only detect activity of a user if they posted in a specific sub-set of channels as determined by the admin?

For example, a server has 2 channels, #1 and #2. A user is only determined as active if they post in #1, so a user is kicked from the server even if they are actively posting in #2 but not #1.

**Comment by benjihiggins** [comment]
You can deny the bot read access to channels you want it to ignore :)
