### ISSUE TITLE
Written documentation link is dead

### ISSUE THREAD

**Issue by kmorris896** [bhigginsuk/discord-activity-monitor#30]
The [written documentation link](https://benjihiggins.github.io/discord-deployment) is now dead.  Any chance you have a cache of this?  The video doesn't show all of the docker options (at least not clearly).

I realize that you aren't actively maintaining this anymore but keeping the documentation up would be extremely helpful.

**Comment by bhigginsuk** [comment]
Thanks for raising this! I have been reorganising my projects etc. lately (including changing my username) and I evidently missed that.
I have fixed the link in the readme now, and [here it is](https://gist.github.com/bhigginsuk/639b321d8ba5795e32c8cf6e46956411) for convenience.
Apologies for any confusion caused.
