### ISSUE TITLE
Bot Auto Shuts down after starting 

### ISSUE THREAD

**Issue by lcswolf** [bhigginsuk/discord-activity-monitor#31]
As soon as I start the bot it shuts down immediately I have attached the log files 
[console.log](https://github.com/bhigginsuk/discord-activity-monitor/files/5504594/console.log)

[debug.log](https://github.com/bhigginsuk/discord-activity-monitor/files/5504593/debug.log)

**Comment by bhigginsuk** [comment]
Hi there, sorry for the delay in reply. Thanks for posting the logs, that's really helpful!
I have a couple of questions:
- Is this a fresh install, or an old one?
- What version are you running?

**Comment by bhigginsuk** [comment]
I think this may be the same as the issue here: https://github.com/bhigginsuk/discord-activity-monitor/issues/32#issuecomment-774329304, in which case it should be fixed with the latest version :+1:
