### ISSUE TITLE
Database Problem

### ISSUE THREAD

**Issue by MannersMatter** [bhigginsuk/discord-activity-monitor#34]
So I followed the steps precisely as you mentioned however I encountered two different problems, a little back story I use Uber bot too, so when a new member comes in he's assigned automatically by the Ub3r bot Pending approval until he provides an intro about himself then we can approve him

so naturally when I invited he bot it got assigned pending approval role

I removed the pending approval role it gave me this screenshot right here

![Capture 2](https://user-images.githubusercontent.com/67511528/110242799-52f04c80-7f60-11eb-803a-8671c067b168.JPG)

when I added the role of a mod (a mod can assign roles remove roles and basically supervise he whole server) it gave me this error here

![Capture 1](https://user-images.githubusercontent.com/67511528/110242827-70bdb180-7f60-11eb-849d-7d427156bba3.JPG)

I don't want to get of my existing bot or system, all I want is to monitor activities on certain channels and to  kick people who hasn't been active for a specific period of time

What am I doing wrong?

Thanks

**Comment by bhigginsuk** [comment]
The first error is to do with the permissions that you've given the Activity Monitor. Or more specifically, with permissions you *haven't* given it. It does a rudimentary check to make sure that it's been given all the permissions necessary before it'll do anything, as operating without the permissions has the potential to cause other issues.
You can check the neccessary permissions for the bot in the Permissions section of the Readme [here](https://github.com/bhigginsuk/discord-activity-monitor#permissions).

As for the second error, that's a pretty generic one to inform you that there is some issue when connecting/reating/writing to the database. Diagnosis depends on your deployment method, but the best thing to do is look in the `debug.log` file the bot creates, if you know how to access it. There should be more information there.
If you are using MongoDB Cloud it might be something as simple as a mistake in the connection string, such as the wrong user or password.

**Comment by bhigginsuk** [comment]
Feel free to reopen this if you're still having issues.
