### ISSUE TITLE
your activity monitor

### ISSUE THREAD

**Issue by Aturok87** [bhigginsuk/discord-activity-monitor#37]
i have a few questions was wondering if you could contact me about some things i have some questions about your bot              
 
Mr. Aturok#1172

**Comment by bhigginsuk** [comment]
What do you need help with?

**Comment by Aturok87** [comment]
well i have updated the bot to discord v12 but all the commands execpt view-config is broken and dont function right i have been makeing changes here and there to make it stable but i dont know how you have the commands programed into the bot and are struggling to fix the commands it wont add or remove roles any more all it does now is start up no errors and it spits out abunch of server names and saying it cant use functions to add remove roles ect

**Comment by Aturok87** [comment]
if you like you can see what i have so far and you can go for there?

**Comment by bhigginsuk** [comment]
I don't have the time to work on this project any more, so I can't fix it for you, but I'll offer some troubleshooting advice.

---

> i have updated the bot to discord v12

Do you mean Node v12? I haven't tested it with anything other than 10 so I don't know if it works. You can use use [nvm](https://github.com/nvm-sh/nvm) to install multiple Node versions side by side, so you should easily be able to use 10.

---

> i have been makeing changes here and there

I'm not going to troubleshoot your changes for you.

---

> how you have the commands programed into the bot

Each bot has it's commands in the folder [src/commands](https://github.com/bhigginsuk/discord-activity-monitor/tree/master/src/commands), where each command has one TypeScript file.
Some of them are shared between all my bots, and are in the shared [disharmony](https://github.com/bhigginsuk/disharmony) project under [src/inbuilt-commands](https://github.com/bhigginsuk/disharmony/tree/master/src/inbuilt-commands).

[disharmony/handle-message.ts](https://github.com/bhigginsuk/disharmony/blob/master/src/core/handle-message.ts) and [disharmony/command-parser.ts](https://github.com/bhigginsuk/disharmony/blob/master/src/commands/command-parser.ts) are responsible for listening for messages and determining if any given message constitutes a command.

---

> saying it cant use functions to add remove roles ect

Make sure the bot has all the permissions [specified in the readme](https://github.com/bhigginsuk/discord-activity-monitor#permissions).
If you are seeing `The bot has not been granted the necessary permissions in this server`, it's telling you these permissions are missing. This is checked in [handle-message.ts](https://github.com/bhigginsuk/disharmony/blob/master/src/core/handle-message.ts#L27) before any commands are processed, as attempting to use the functionality without enough permissions can break things.

**Comment by Aturok87** [comment]
Thank you this helps me out ALOT! and discord made some bot breaking changed with slash commands and updating push and pull requests for bots some bot never went down I got the bot working for 11 and now 11 is forced obsolete so I have been working on getting it working for 12 and thank you so much again for clarifying where to find things I can def get the commands running again now for sure!!!

**Comment by bhigginsuk** [comment]
Glad I could help. Sorry this project isn't maintained any more.

**Comment by Aturok87** [comment]
That's ok when the project was shut down I picked it up and had been hosting it since then making modifications tweaking things here and there and keeping it alive and was hosting it on my server PC for close to 3 years

**Comment by verwischt** [comment]
Hello, Aturo. will you make BOT available on github just like Benjamin Higgins did? That would be awesome!

**Comment by Aturok87** [comment]
No I will self host it for all to use I have a server PC that runs the bot
